### ISSUE TITLE
Getting wrong colours

### ISSUE THREAD

**Issue by Snakehips** [mar3kk/threekkapps_library#1]
Flood fill works fine with alpha set to FF. But when set to a lower value the rgb values are not maintained. I get wrong colours. Any helps appreciated.

**Comment by mar3kk** [comment]
I'll look at it.

**Comment by Snakehips** [comment]
Thanks for getting back to me. Please find below the results I get
Hope this is usefull.

Input  (ARGB)     Output
 BLACK  FF000000 FF000000  80000000 80000000  40000000 40000000  RED
FFFF0000 FFFF0000  80FF0000 80FB0000  40FF0000 40F70000  GREEN  FF00FF00
FF00FF00  8000FF00 8000FB00  4000FF00 4000F700  BLUE  FF0000FF FF0000FF
800000FF 800000FB  400000FF 400000F7  WHITE  FFFFFFFF FFFFFFFF  80FFFFFF
80FBFBFB  40FFFFFF 40F7F7F7  Complex colour 1  FF7846BE FF7846BE  807846BE
80EF8B7C  407846BE 40DF18F3  Complex colour 2  FFBE465A FFBE465A  80BE465A
807C8BB3  40BE465A 40F31868

**Comment by mar3kk** [comment]
Issue resolved. Sorry for this long response delay.

**Comment by Snakehips** [comment]
Thanks for the update.
